import test from 'node:test';
import assert from 'node:assert/strict';
import {Invaders} from '../games/shared/precision/invaders.js';
import {Breakout} from '../games/shared/precision/breakout.js';
import {Asteroids} from '../games/shared/precision/asteroids.js';
import {Enduro,roadProjection,trafficHit} from '../games/shared/retro/enduro.js';
import {paddle,cannon,ship} from './fixtures/precision-routes.mjs';
const dt=1/120;
function run(m,sec,control=()=>({})){for(let n=0;n<sec*120&&!m.done;n++)m.step(dt,control(m));}
test('Breakout completes both 112-brick walls at 896 using speed-limited pointer inputs',()=>{const m=new Breakout();run(m,400,paddle);assert.equal(m.won,true);assert.equal(m.score,896);assert.equal(m.cleared,224);assert.equal(m.wave,2);assert.equal(m.lives,5);});
test('Breakout swept collisions stop high-speed tunneling and reflect from a side',()=>{const m=new Breakout();m.waiting=false;m.bricks.forEach(b=>b.alive=false);const b=m.bricks[60];b.alive=true;const other=m.bricks[0];other.alive=true;m.ball={x:b.x-10,y:b.y+6,vx:2000,vy:0,r:3};m.step(dt);assert.equal(b.alive,false);assert(m.ball.vx<0);assert.equal(m.score,b.points);});
test('Breakout paddle contact controls rebound and ceiling halves width until a lost ball',()=>{const m=new Breakout();m.waiting=false;m.ball={x:m.x+20,y:406,vx:10,vy:205,r:3};m.step(dt);assert(m.ball.vx>100);assert(m.ball.vy<0);m.ball={x:180,y:18,vx:1,vy:-250,r:3};m.step(dt);assert.equal(m.width,29);assert(m.ball.vy>0);m.ball.y=459;m.ball.vy=200;m.step(dt);assert.equal(m.lives,4);assert.equal(m.width,58);assert(m.waiting);});
test('Invaders has 36 aliens, 630 points per formation and one cannon shot at a time',()=>{const m=new Invaders();m.x=125;assert.equal(m.remaining,36);assert.equal(m.aliens.reduce((s,a)=>s+(6-a.row)*5,0),630);m.step(dt,{action:true});const shot=m.shot;run(m,.1,()=>({action:true}));assert.equal(m.shot,shot);assert.equal(m.score,0);assert.equal(m.lives,3);});
test('Invaders shields erode from both directions and repeat shots create a real tunnel',()=>{const m=new Invaders();const before=m.shields.filter(s=>s.alive).length;assert(m.shieldHit({x:65,y:390},-70));assert(m.shields.filter(s=>s.alive).length<before);for(let n=0;n<12;n++)m.shieldHit({x:65,y:390},-70);assert.equal(m.shieldHit({x:65,y:390},-70),false);const after=m.shields.filter(s=>s.alive).length;assert(m.shieldHit({x:167,y:330},70));assert(m.shields.filter(s=>s.alive).length<after);});
test('Invaders speeds up, reverses at the surviving edge, awards the command ship and ends on invasion',()=>{const m=new Invaders();const slow=m.interval;m.aliens.forEach((a,i)=>a.alive=i===0);assert(m.interval<slow/3);m.formation.x=343;m.moveClock=m.interval;m.step(dt);assert.equal(m.formation.dir,-1);assert.equal(m.formation.y,75);m.ufo={x:180,y:25,dir:1};m.shot={x:180,y:35};run(m,.02);assert.equal(m.score,200);m.formation.y=407;m.step(dt);assert(m.done);assert.match(m.message,/Terra/);});
test('Invaders normal controls clear four complete waves without invulnerability or state edits',()=>{const m=new Invaders();run(m,150,cannon);assert(m.wave>=5);assert(m.score>=4*630);assert(m.done);assert.equal(m.lives,0);});
test('Asteroids preserves momentum, wraps the ship, and caps simultaneous torpedoes',()=>{const m=new Asteroids();run(m,.5,()=>({up:true}));const vx=m.ship.vx,vy=m.ship.vy;run(m,.2);assert.equal(m.ship.vx,vx);assert.equal(m.ship.vy,vy);m.ship.x=359;m.ship.vx=200;m.step(dt);assert(m.ship.x<2);run(m,.8,()=>({action:true}));assert(m.bullets.length<=4);});
test('Asteroid fragments conserve the size tree and grant 20/50/100 points plus a bonus ship',()=>{const m=new Asteroids();m.rocks=[m.rock(30,30,3,0)];m.destroy(m.rocks[0]);assert.deepEqual(m.rocks.map(r=>r.size),[2,2]);assert.equal(m.score,20);m.destroy(m.rocks[0]);assert.equal(m.score,70);const small=m.rocks.find(r=>r.size===1);m.destroy(small);assert.equal(m.score,170);m.addScore(4830);assert.equal(m.lives,5);assert.equal(m.extra,10000);});
test('Asteroids bullets hit across screen seams and hyperspace cannot repeat while held',()=>{const m=new Asteroids();m.rocks=[m.rock(1,100,1,0),m.rock(180,20,3,0)];m.rocks[0].vx=m.rocks[0].vy=0;m.bullets=[{x:357,y:100,vx:400,vy:0,life:1}];m.step(dt);assert.equal(m.score,100);m.ship.vx=m.ship.vy=0;m.step(dt,{down:true});const point={x:m.ship.x,y:m.ship.y};run(m,.5,()=>({down:true}));assert.equal(m.ship.x,point.x);assert.equal(m.ship.y,point.y);assert(m.hyperCooldown>1);});
test('Asteroids legal thrust/rotation/fire/hyperspace inputs clear three complete fields',()=>{const m=new Asteroids();run(m,150,ship);assert(m.wave>=4);assert(m.score>=7500);assert.equal(m.lives,0);assert(m.done);});
test('All new games freeze score and movement after final defeat',()=>{for(const Model of [Breakout,Invaders,Asteroids]){const m=new Model();if(m instanceof Breakout){for(let i=0;i<5;i++)m.lose();}else{m.invulnerable=0;for(let i=m.lives;i>0;i--){m.dead=0;m.lose();}}assert(m.done);const snap=JSON.stringify(m);m.step(1,{action:true,up:true,right:true});assert.equal(JSON.stringify({...m,events:[]}),JSON.stringify({...JSON.parse(snap),events:[]}));}});
test('Enduro collision follows projected bodies and roadside never accelerates a stopped car',()=>{const m=new Enduro();m.distance=3100;m.x=0;const near={x:0,z:0};assert(trafficHit(m,near));assert.equal(trafficHit(m,{x:.6,z:0}),false);assert.equal(trafficHit(m,{x:0,z:100}),false);const r=roadProjection(m,0);assert.equal(r.x,80);assert.equal(r.y,155);m.x=1.2;run(m,.5);assert.equal(m.speed,0);});

test('Asteroid contacts use the rendered polygon, allowing shots past empty bounding-circle corners',()=>{const m=new Asteroids();const r=m.rock(100,100,1,0);Object.assign(r,{vx:0,vy:0,spin:0,angle:0,shape:[1,1,1,1]});m.rocks=[r];m.bullets=[{x:108,y:105,vx:0,vy:50,life:1}];m.step(dt);assert.equal(m.score,0);m.bullets=[{x:100,y:85,vx:0,vy:1000,life:1}];m.step(dt);assert.equal(m.score,100);});
test('Optional challenge modes change enemy fire without changing classic rules',()=>{const normal=new Invaders(),fast=new Invaders({variant:'fast'});for(const m of [normal,fast])m.bombs=[{x:18,y:250,baseX:18,age:0}];run(normal,.2);run(fast,.2);assert(fast.bombs[0].y>normal.bombs[0].y+10);assert.notEqual(fast.bombs[0].x,18);const a=new Asteroids({variant:'expert'}),b=new Asteroids();a.ufoClock=b.ufoClock=.01;run(a,.05);run(b,.05);assert(a.ufo);assert.equal(b.ufo,null);run(a,1.2);assert(a.enemyBullets.length>0);});
