import {Invaders} from './invaders.js';
import {Breakout} from './breakout.js';
import {Asteroids} from './asteroids.js';
import {render} from './render.js';
const defs={
 'space-invaders':{title:'SPACE INVADERS',Model:Invaders,action:'ATIRAR',hint:'← → mover · Espaço atirar · P pausar',intro:'Proteja a Terra. Um tiro de cada vez.',rules:['36 invasores por onda. Eles aceleram quando restam poucos.','Os três escudos se desgastam com tiros dos dois lados.','Cada invasor vale de 5 a 30 pontos; a nave vermelha vale 200.','3 vidas. Se a formação alcançar o chão, a partida termina.'],variants:[['classic','Clássico'],['fast','Bombas rápidas']]},
 breakout:{title:'BREAKOUT',Model:Breakout,action:'SACAR',hint:'Arraste a raquete · ← → mover · Espaço sacar',intro:'Abra uma passagem e mande a bola para trás do muro.',rules:['5 bolas para derrubar dois muros de 112 tijolos.','As bordas da raquete produzem rebotes mais inclinados.','A bola acelera durante a jogada; tocar o teto reduz a raquete.','Vermelho: 7 · laranja: 5 · verde: 3 · amarelo: 1. Máximo: 896.'],variants:[]},
 asteroids:{title:'ASTEROIDS',Model:Asteroids,action:'ATIRAR',hint:'← → girar · ↑ impulso · Espaço tiro · ↓ hiperespaço',intro:'Gire, acelere e controle a inércia da nave.',rules:['4 naves. Uma nave extra a cada 5.000 pontos.','Pedras grandes se dividem em médias; médias viram pequenas.','20, 50 ou 100 pontos por pedra. Nave, pedras e tiros cruzam as bordas.','O hiperespaço muda sua posição, mas pode levar você a uma colisão.','No modo Desafio, satélites e discos inimigos também atiram.'],variants:[['classic','Clássico'],['expert','Desafio']]}
};
const $=id=>document.getElementById(id),kind=document.body.dataset.game,cfg=defs[kind],canvas=$('canvas'),ctx=canvas.getContext('2d'),keys=new Set(),held=new Map();
let model=new cfg.Model(),state='menu',variant='classic',best=0,muted=false,crt=false,storage,last=0,acc=0,countdown=0,sent=false,targetX=null,dragPointer=null,audioCtx,previousPause=false,lastAnnouncement=0;
try{storage=localStorage;muted=storage.getItem('cooked:precision:muted')==='true';crt=storage.getItem('cooked:precision:crt')==='true';}catch{}
const persist=(k,v)=>{try{storage?.setItem(k,String(v));}catch{}};
const scoreKey=()=>`cooked:precision:v1:${kind}:${variant}`;
function readBest(){try{best=Number(storage?.getItem(scoreKey()))||0;}catch{best=0;}if(!Number.isFinite(best)||best<0)best=0;}
$('name').textContent=cfg.title;$('action').textContent=cfg.action;$('hint').textContent=cfg.hint;canvas.setAttribute('aria-label',cfg.title+'. '+cfg.hint);
for(const rule of cfg.rules){const li=document.createElement('li');li.textContent=rule;$('rules').append(li);}
for(const [value,label]of cfg.variants){const o=document.createElement('option');o.value=value;o.textContent=label;$('variant').append(o);}
$('mode-row').hidden=!cfg.variants.length;
if(kind==='breakout'){$('drag').hidden=false;$('left').hidden=true;$('right').hidden=true;}
if(kind==='asteroids'){$('left').textContent='↶';$('right').textContent='↷';$('left').setAttribute('aria-label','Girar para a esquerda');$('right').setAttribute('aria-label','Girar para a direita');$('thrust').hidden=false;$('hyper').hidden=false;}
function clear(){held.clear();keys.clear();targetX=null;dragPointer=null;for(const b of document.querySelectorAll('.held'))b.classList.remove('held');}
function setState(next){state=next;document.body.dataset.state=next;for(const b of document.querySelectorAll('[data-input],#drag'))b.disabled=next!=='playing';$('pause').disabled=!['playing','countdown'].includes(next);}
function settings(){$('sound').textContent=muted?'Som: desligado':'Som: ligado';$('sound').setAttribute('aria-pressed',String(!muted));$('crt').setAttribute('aria-pressed',String(crt));$('screen').classList.toggle('crt',crt);}
function unlockAudio(){if(muted)return;try{audioCtx||=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume().catch(()=>{});}catch{}}
function tone(event){if(muted||audioCtx?.state!=='running')return;const sounds={shoot:[700,160,.07],march:[80+(model.animation%4)*14,60,.045],brick:[500,750,.065],bounce:[260,200,.055],hit:[100,22,.4],destroy:[200,45,.15],bonus:[520,1200,.3],clear:[400,900,.4],hyper:[900,80,.3],serve:[330,550,.12],shrink:[750,250,.15]};const s=sounds[event];if(!s)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime;o.type=event==='destroy'?'sawtooth':'square';o.frequency.setValueAtTime(s[0],t);o.frequency.exponentialRampToValueAtTime(s[1],t+s[2]);g.gain.setValueAtTime(event==='march'?.009:.025,t);g.gain.exponentialRampToValueAtTime(.001,t+s[2]);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(t+s[2]);o.onended=()=>{o.disconnect();g.disconnect();};}
function menu(title,copy,button){$('title').textContent=title;$('intro').textContent=copy;$('start').textContent=button;$('overlay').hidden=false;$('restart').hidden=state!=='paused';$('mode-row').hidden=!cfg.variants.length||state==='paused';$('variant').disabled=state==='paused';$('best').textContent=`RECORDE ${Math.floor(best).toLocaleString('pt-BR')} · salvo neste aparelho`;}
function start(){unlockAudio();clear();if(state!=='paused'){variant=$('variant').value||'classic';readBest();model=new cfg.Model({variant});sent=false;}countdown=.9;setState('countdown');$('overlay').hidden=true;$('countdown').hidden=false;last=0;acc=0;canvas.focus({preventScroll:true});}
function pause(){if(!['playing','countdown'].includes(state))return;setState('paused');clear();$('countdown').hidden=true;menu('Jogo pausado','Continue quando quiser.','Continuar');$('start').focus({preventScroll:true});}
function finish(){setState('finished');clear();best=Math.max(best,model.score);persist(scoreKey(),best);menu(model.won?'MUITO BEM!':'FIM DE JOGO',`${model.score.toLocaleString('pt-BR')} pontos. ${model.message}`,'Jogar novamente');$('start').focus({preventScroll:true});if(!sent){sent=true;if(parent!==window)parent.postMessage({type:'cooked:round-complete',game:kind},location.origin);}}
$('start').onclick=start;$('pause').onclick=pause;$('restart').onclick=()=>{setState('menu');start();};$('help-toggle').onclick=()=>{$('help').hidden=!$('help').hidden;$('help-toggle').setAttribute('aria-expanded',String(!$('help').hidden));};$('sound').onclick=()=>{muted=!muted;persist('cooked:precision:muted',muted);unlockAudio();settings();};$('crt').onclick=()=>{crt=!crt;persist('cooked:precision:crt',crt);settings();};$('variant').onchange=()=>{variant=$('variant').value;readBest();$('best').textContent=`RECORDE ${best} · salvo neste aparelho`;};
for(const b of document.querySelectorAll('[data-input]')){
 b.onpointerdown=e=>{if(state!=='playing')return;e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,b.dataset.input);b.classList.add('held');unlockAudio();};
 const release=e=>{held.delete(e.pointerId);if(![...held.values()].includes(b.dataset.input))b.classList.remove('held');};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;
 b.onclick=e=>{if(e.detail===0&&state==='playing'){const k=Symbol(b.dataset.input);held.set(k,b.dataset.input);setTimeout(()=>held.delete(k),130);}};
}
function pointerTarget(e,el){const r=el.getBoundingClientRect();targetX=Math.max(0,Math.min(360,(e.clientX-r.left)/r.width*360));}
for(const el of [canvas,$('drag')]){el.addEventListener('pointerdown',e=>{if(state!=='playing'||kind!=='breakout')return;e.preventDefault();el.setPointerCapture(e.pointerId);dragPointer=e.pointerId;pointerTarget(e,el);});el.addEventListener('pointermove',e=>{if(e.pointerId===dragPointer)pointerTarget(e,el);});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,e=>{if(e.pointerId===dragPointer)dragPointer=null;});}
const map={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',Space:'action'};
document.addEventListener('keydown',e=>{if(['Escape','KeyP'].includes(e.code)){if(e.repeat)return;e.preventDefault();if(state==='paused')start();else pause();return;}if(e.code==='Enter'&&['menu','paused','finished'].includes(state)){e.preventDefault();start();return;}if(state==='playing'&&map[e.code]){e.preventDefault();keys.add(e.code);if(['left','right'].includes(map[e.code]))targetX=null;}});document.addEventListener('keyup',e=>keys.delete(e.code));
window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='cooked:pause')pause();});
function controls(){const out={};for(const name of held.values())out[name]=true;for(const key of keys)out[map[key]]=true;if(targetX!==null)out.targetX=targetX;try{const p=[...(navigator.getGamepads?.()||[])].find(p=>p?.connected);if(p){out.left||=p.axes[0]<-.25||p.buttons[14]?.pressed;out.right||=p.axes[0]>.25||p.buttons[15]?.pressed;out.up||=p.buttons[0]?.pressed||p.buttons[12]?.pressed;out.action||=p.buttons[1]?.pressed||p.buttons[7]?.pressed;out.down||=p.buttons[2]?.pressed||p.buttons[13]?.pressed;if(kind!=='asteroids')out.action||=p.buttons[0]?.pressed;const pressed=!!p.buttons[9]?.pressed;if(pressed&&!previousPause){if(state==='playing')pause();else if(state==='paused')start();}previousPause=pressed;}}catch{}return out;}
function resize(){const r=$('play-area').getBoundingClientRect(),width=Math.max(80,Math.min(r.width-24,(r.height-4)*.8,580));$('screen').style.width=width+'px';$('screen').style.height=width*1.25+'px';}
new ResizeObserver(resize).observe($('play-area'));
function frame(now){const dt=last?Math.min(.1,(now-last)/1000):0;last=now;const input=controls();if(state==='countdown'){countdown-=dt;$('countdown').textContent=countdown>.25?'1':'VAI!';if(countdown<=0){$('countdown').hidden=true;setState('playing');}}if(state==='playing'){acc+=dt;while(acc>=1/120){model.step(1/120,input);for(const e of model.events)tone(e);acc-=1/120;if(model.done){finish();break;}}}render(ctx,kind,model);$('score').textContent=String(model.score).padStart(5,'0');$('wave').textContent=String(model.wave).padStart(2,'0');$('lives').textContent=String(model.lives).padStart(2,'0');if(kind==='asteroids')$('hyper').textContent=model.hyperCooldown?`HIPERESPAÇO · ${Math.ceil(model.hyperCooldown)}s`:'HIPERESPAÇO';if(now-lastAnnouncement>1000){$('status').textContent=`${model.score} pontos. Onda ${model.wave}. ${model.lives} vidas.`;lastAnnouncement=now;}requestAnimationFrame(frame);}
readBest();settings();setState('menu');menu('Pronto para jogar?',cfg.intro,'Jogar');resize();requestAnimationFrame(frame);
