import { CONFIG, MODELS, WIDTH, HEIGHT, clamp } from './models.js';
import { Renderer, loadArt } from './render.js';
import { readProgress, saveResult } from '../progress.js';
const $=id=>document.getElementById(id),kind=document.body.dataset.game,config=CONFIG[kind],isRider=kind==='sunset-rider',isDefense=kind==='sky-bastion';
let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{}};}
const progress=readProgress(storage,kind,3),canvas=$('canvas'),keys=new Set(),held=new Map();
let level=progress.unlocked,model=new MODELS[kind](level),state='menu',renderer,assetError=false,last=0,accumulator=0,countdown=0,roundSent=false,targetX,targetY,steerId,dragOrigin,action=false,leftStep=false,rightStep=false,target,fire=false,audio,sound=true;
try{sound=storage.getItem('cooked:sound')!=='off';}catch{}
document.documentElement.style.setProperty('--accent',config.accent);$('name').textContent=config.title;$('hint').textContent=config.hint;
const icon=(paths)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths}</svg>`;
$('pause').innerHTML=icon('<path d="M8 5v14M16 5v14" stroke-width="4"/>');
$('left').innerHTML=icon('<path d="m14 5-7 7 7 7"/>');$('right').innerHTML=icon('<path d="m10 5 7 7-7 7"/>');
$('left').setAttribute('aria-label',isDefense?'Aim left':'Move left');$('right').setAttribute('aria-label',isDefense?'Aim right':'Move right');
canvas.setAttribute('aria-label',`${config.title}. ${config.instructions} Keyboard: arrow keys or WASD to ${isDefense?'aim':'move'}, Space to ${isDefense?'fire':config.action.toLowerCase()}. P to pause.`);
function audioStart(){try{audio||=new (window.AudioContext||window.webkitAudioContext)();if(sound)audio.resume().catch(()=>{});}catch{}}
let lastShotSound=0;
function effect(name){if(!sound||audio?.state!=='running')return;const time=audio.currentTime;if(name==='shot'&&time-lastShotSound<.15)return;if(name==='shot')lastShotSound=time;const hz={shot:620,launch:450,spark:390,burst:150,hit:72,pickup:880,near:720,checkpoint:1046,win:1320,end:92,pulse:190,warning:210,shield:520}[name];if(!hz)return;const osc=audio.createOscillator(),gain=audio.createGain();const duration=name==='win'?.55:name==='hit'?.22:.1;osc.type=['hit','burst','end'].includes(name)?'sawtooth':'triangle';osc.frequency.setValueAtTime(hz,time);osc.frequency.exponentialRampToValueAtTime(hz*(name==='hit'?.3:1.3),time+duration);gain.gain.setValueAtTime(name==='shot'?.009:.025,time);gain.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(time+duration+.01);}
function soundUI(){ $('sound').innerHTML=sound?icon('<path d="m11 5-6 4H2v6h3l6 4V5Zm4 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>'):icon('<path d="m11 5-6 4H2v6h3l6 4V5Zm5 4 5 6m0-6-5 6"/>');$('sound').setAttribute('aria-label',sound?'Turn sound off':'Turn sound on');$('sound').setAttribute('aria-pressed',String(sound));}
$('sound').onclick=()=>{sound=!sound;try{storage.setItem('cooked:sound',sound?'on':'off');}catch{}audioStart();soundUI();};soundUI();
function clearInput(){keys.clear();held.clear();targetX=targetY=steerId=dragOrigin=target=undefined;action=fire=leftStep=rightStep=false;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}
function change(next){state=next;document.body.dataset.state=next;$('pause').disabled=state!=='playing'&&state!=='countdown';for(const b of document.querySelectorAll('.control'))b.disabled=state!=='playing';}
function missions(){ $('missions').replaceChildren();config.stages.forEach((name,i)=>{const b=document.createElement('button');b.className='mission';b.type='button';b.disabled=i>progress.unlocked;b.setAttribute('aria-pressed',String(i===level));b.setAttribute('aria-label',`${i+1}. ${name}${b.disabled?', locked':''}`);const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0');const title=document.createElement('strong');title.textContent=name;const stars=document.createElement('span');stars.className='stars';stars.textContent=b.disabled?'LOCKED':progress.medals[i]?'★'.repeat(progress.medals[i]):'—';b.append(n,title,stars);b.onclick=()=>{level=i;model=new MODELS[kind](level);missions();best();};$('missions').append(b);}); }
function best(){$('best').textContent=`${config.stages[level]} · ${progress.scores[level]?'Best '+progress.scores[level].toLocaleString():'Set your first record'}`;}
function overlay(title,copy,label,button){$('title').textContent=title;$('instructions').textContent=copy;$('eyebrow').textContent=label;$('start').textContent=button;$('overlay').hidden=false;$('start').disabled=!renderer&&!assetError;$('missions').hidden=state!=='menu';$('menu').hidden=state==='menu';$('retry').hidden=state!=='paused';if(state==='paused')$('retry').textContent='Restart mission';$('best').hidden=state==='paused';best();}
function menu(){clearInput();change('menu');model=new MODELS[kind](level);missions();overlay(config.title,config.instructions,'CHOOSE YOUR MISSION',renderer?'Start mission':'Loading artwork…');}
function start(){$('announcement').textContent='';if(assetError){location.reload();return;}if(!renderer)return;audioStart();clearInput();if(state!=='paused'){if(state==='finished'&&model.won&&level<2)level++;model=new MODELS[kind](level);roundSent=false;}countdown=state==='paused'?.65:1.6;change('countdown');$('overlay').hidden=true;$('countdown').hidden=false;canvas.focus({preventScroll:true});last=0;accumulator=0;}
function pause(){if(state!=='playing'&&state!=='countdown')return;change('paused');clearInput();$('countdown').hidden=true;overlay('Paused','Take your time. Your mission will resume right here.',config.title.toUpperCase(),'Resume');$('start').focus({preventScroll:true});}
function complete(){change('finished');clearInput();saveResult(storage,kind,progress,level,model);overlay(model.won?'Mission complete':'One more try?',model.message,model.won?'★'.repeat(model.medal)+'  '+Math.floor(model.score).toLocaleString()+' POINTS':config.stages[level].toUpperCase(),model.won&&level<2?'Next mission':'Play again');$('retry').hidden=!model.won||level===2;$('retry').textContent='Replay mission';$('announcement').textContent=`${model.won?'Mission complete':'Game over'}. Score ${Math.floor(model.score)}.`;if(!roundSent){roundSent=true;if(parent!==window)parent.postMessage({type:'cooked:round-complete',game:kind},location.origin);}$('start').focus({preventScroll:true});}
$('start').onclick=start;$('pause').onclick=pause;$('menu').onclick=menu;$('retry').onclick=()=>{change('menu');start();};
function pulse(name){if(name==='left')leftStep=true;if(name==='right')rightStep=true;if(name==='action')action=true;}
for(const name of ['left','right','action']){const b=$(name);b.onpointerdown=e=>{if(state!=='playing')return;e.preventDefault();audioStart();b.setPointerCapture(e.pointerId);held.set(e.pointerId,name);b.classList.add('held');pulse(name);};const release=e=>{held.delete(e.pointerId);if(![...held.values()].includes(name))b.classList.remove('held');};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;b.onclick=e=>{if(e.detail===0&&state==='playing')pulse(name);};}
function point(e){const r=canvas.getBoundingClientRect();return{x:clamp((e.clientX-r.left)*WIDTH/r.width,0,WIDTH),y:clamp((e.clientY-r.top)*HEIGHT/r.height,0,HEIGHT)};}
canvas.onpointerdown=e=>{if(state!=='playing')return;e.preventDefault();audioStart();const p=point(e);if(isDefense){target=p;return;}if(steerId!==undefined)return;steerId=e.pointerId;canvas.setPointerCapture(e.pointerId);dragOrigin={x:p.x,y:p.y,shipX:model.x,shipY:model.y,lane:model.lane};if(isRider)targetX=p.x;else{targetX=model.x;targetY=model.y;}};
canvas.onpointermove=e=>{if(state!=='playing'||e.pointerId!==steerId||!dragOrigin)return;const p=point(e);if(isRider){if(Math.abs(p.x-dragOrigin.x)>24)targetX=model.x+(p.x-dragOrigin.x)*1.5;else targetX=p.x;}else{targetX=dragOrigin.shipX+p.x-dragOrigin.x;targetY=dragOrigin.shipY+p.y-dragOrigin.y;}};
const release=e=>{if(e.pointerId===steerId){steerId=targetX=targetY=dragOrigin=undefined;}};canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onlostpointercapture=release;
document.addEventListener('keydown',e=>{if(['KeyP','Escape'].includes(e.code)){if(state==='playing'||state==='countdown'){e.preventDefault();pause();}return;}if(state!=='playing'||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyA','KeyD','KeyW','KeyS','Space'].includes(e.code))return;e.preventDefault();keys.add(e.code);if(!e.repeat){if(['ArrowLeft','KeyA'].includes(e.code))leftStep=true;if(['ArrowRight','KeyD'].includes(e.code))rightStep=true;if(e.code==='Space'){if(isDefense)fire=true;else action=true;}}});
document.addEventListener('keyup',e=>keys.delete(e.code));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='cooked:pause')pause();});
const heldName=name=>[...held.values()].includes(name);function input(){return{left:keys.has('ArrowLeft')||keys.has('KeyA')||heldName('left'),right:keys.has('ArrowRight')||keys.has('KeyD')||heldName('right'),up:keys.has('ArrowUp')||keys.has('KeyW'),down:keys.has('ArrowDown')||keys.has('KeyS'),targetX,targetY,leftStep,rightStep,action:isRider?(heldName('action')||keys.has('Space')||action):action,target,fire:fire||(isDefense&&keys.has('Space'))};}
function resize(){const r=$('arena').getBoundingClientRect(),scale=Math.max(.1,Math.min(r.width/WIDTH,r.height/HEIGHT)),dpr=Math.min(2,devicePixelRatio||1);canvas.style.width=WIDTH*scale+'px';canvas.style.height=HEIGHT*scale+'px';canvas.width=Math.round(WIDTH*dpr);canvas.height=Math.round(HEIGHT*dpr);canvas.getContext('2d').setTransform(dpr,0,0,dpr,0,0);}new ResizeObserver(resize).observe($('arena'));resize();
let lastHull=-1;function hud(){ $('score').textContent=String(Math.floor(model.score)).padStart(5,'0');if(lastHull!==model.hull){lastHull=model.hull;$('lives').innerHTML=Array.from({length:3},(_,i)=>`<svg viewBox="0 0 24 24" aria-hidden="true" class="${i<model.hull?'':'empty'}"><path d="M12 21 3 12C-3 5 5-2 12 5c7-7 15 0 9 7Z"/></svg>`).join('');$('lives').setAttribute('aria-label',`${model.hull} ${isDefense?'cities':'hull points'} remaining`);}const amount=isRider?model.energy:isDefense?model.energy/6*100:model.charges/2*100;$('action').style.setProperty('--charge',clamp(amount,0,100)+'%');$('action-label').textContent=isRider?`TURBO · ${Math.round(model.energy)}%`:isDefense?model.emp>0?`EMP · ${Math.ceil(model.emp)}s`:`EMP · ${Math.floor(model.energy)}/6 ENERGY`:`PULSE · ${model.charges} LEFT`; }
function frame(time){const dt=last?Math.min(.06,(time-last)/1000):0;last=time;if(state==='countdown'){countdown-=dt;$('countdown').textContent=countdown>.5?'READY':'GO';if(countdown<=0){change('playing');$('countdown').hidden=true;}}
 if(state==='playing'){accumulator+=dt;while(accumulator>=1/120&&state==='playing'){model.tick(1/120,input());action=leftStep=rightStep=fire=false;target=undefined;accumulator-=1/120;for(const event of model.events.splice(0))effect(event);if(model.done)complete();}}
 renderer?.draw(model,state==='playing');hud();requestAnimationFrame(frame);}
menu();loadArt().then(art=>{renderer=new Renderer(canvas,kind,art);$('start').disabled=false;$('start').textContent='Start mission';}).catch(()=>{assetError=true;$('start').disabled=false;$('start').textContent='Reload game';$('instructions').textContent='Game artwork could not load. Please reload to try again.';});requestAnimationFrame(frame);
